apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: tomasbeltran/cartservice:latest
          ports:
<<<<<<< HEAD
            - containerPort: 50051
=======
            - containerPort: 50051
>>>>>>> 2e2b8f6ab1d25c71016c93c3e9ad85638acbfe55
