apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: tomasbeltran/shippingservice:latest
          ports:
<<<<<<< HEAD
            - containerPort: 50051
=======
            - containerPort: 50051
>>>>>>> 0c338fae36ee9a2f90aefdf19d210a6f45731163
