apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
resources:
  - ../../base

patches:
  - path: patch.yaml

images:
  - name: tomasbeltran/checkoutservice
    newTag: latest
