apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
resources:
  - ../../base

patches:
  - path: patch.yaml

images:
  - name: tomasbeltran/productcatalogservice
    newTag: latest
